### ISSUE TITLE
Streamify

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/stacker-of-worlds#1]
As the time approaches that this module might be used, it cannot pretend any longer that large GeoJSON files do not exist.

It should use [geojson-stream](https://github.com/mapbox/geojson-stream) to stream through features (instead of expecting them all to be loaded into memory) then output a stream of stacked features (instead of a file).

cc @rclark

**Comment by mapsam** [comment]
"streamer-of-worlds"

**Comment by davidtheclark** [comment]
When implementing streaming features, we'll want to make sure to also expose the function that transforms the feature itself. This function could be used in non-streaming contexts, like a browser.
